# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1db9db7a87d1d1f55ea2d1e1f8697544293af64e16f2ea00f6197f0c3096daa365ac2da5cce9b41bcb06cf5ee8f264d61dca08c7c9b54a7496e7f9f5dd29cd4d

test:
  secret_key_base: 53d6d7dd919d5a6c5c69dfc7b88d365af7b6f595a4e9a5b4fdadbec697acaf32b0963260e49c70aae8fe2940804ba12084902ecc6a4116539769d0d55c2b7285

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
